appName: myhelmapp

configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'This app was deployed with helm!'

image:
  name: njajula/helm-webapp
  tag: 35

service:
  type: ClusterIP
  port: 80
